export type Project = {
    id: number;
    active: boolean;
    column: string;
    name: string;
    path: string;
    summary: string;
    type: string;
    team: string;
    role: string;
    medium: string;
    tools: string;
    year: number;
    tags: string;
    vertical: boolean;
    frontImage: string;
    frontImageBG: string;
    border: boolean;
    description: string;
};